name: mne_bids
channels:
- defaults
- conda-forge
dependencies:
- python<=3.8
- pip
- mkl
- numpy>=1.15.4
- scipy>=1.1.0
- scikit-learn>=0.20.2
- matplotlib
- pip:
  - mne_bids
  - mne>=0.21.0
  - nibabel
  - pybv>=0.2.0
  - nilearn
  - flake8
  - pytest<5.4
  - pytest-cov
  - pytest-sugar
  - check-manifest
  - pydocstyle
  - sphinx
  - pillow
  - numpydoc
  - sphinx_bootstrap_theme
  - sphinx_gallery

